export type OscKind = "sine" | "square" | "sawtooth" | "triangle";

export type Preset = {
  id: string;
  name: string;
  group: string;
  clef: "treble" | "bass" | "grand";
  gain: number;
  attack: number;
  decay: number;
  sustain: number;
  release: number;
  filter: number;
  filterQ: number;
  filterEnv: number;
  vibrato: number;
  partials: { type: OscKind; ratio: number; gain: number; detune?: number }[];
  fm?: { ratio: number; index: number; decay: number };
};

export const PRESETS: Preset[] = [
  {
    id: "piano",
    name: "Grand piano",
    group: "Keys",
    clef: "grand",
    gain: 0.28,
    attack: 0.006,
    decay: 0.42,
    sustain: 0.18,
    release: 0.35,
    filter: 2200,
    filterQ: 0.4,
    filterEnv: 2800,
    vibrato: 0,
    partials: [
      { type: "sine", ratio: 1, gain: 1 },
      { type: "sine", ratio: 2, gain: 0.38 },
      { type: "sine", ratio: 3, gain: 0.16 },
      { type: "sine", ratio: 4, gain: 0.08 },
      { type: "triangle", ratio: 1, gain: 0.18 },
    ],
  },
  {
    id: "epiano",
    name: "Electric piano",
    group: "Keys",
    clef: "grand",
    gain: 0.32,
    attack: 0.008,
    decay: 0.5,
    sustain: 0.12,
    release: 0.28,
    filter: 2400,
    filterQ: 0.6,
    filterEnv: 800,
    vibrato: 0,
    partials: [],
    fm: { ratio: 2, index: 1.6, decay: 0.45 },
  },
  {
    id: "organ",
    name: "Organ",
    group: "Keys",
    clef: "grand",
    gain: 0.18,
    attack: 0.02,
    decay: 0.05,
    sustain: 0.9,
    release: 0.12,
    filter: 3200,
    filterQ: 0.2,
    filterEnv: 0,
    vibrato: 0.004,
    partials: [
      { type: "sine", ratio: 1, gain: 0.7 },
      { type: "sine", ratio: 2, gain: 0.45 },
      { type: "sine", ratio: 3, gain: 0.28 },
      { type: "sine", ratio: 4, gain: 0.18 },
      { type: "sine", ratio: 6, gain: 0.1 },
    ],
  },
  {
    id: "harp",
    name: "Harp",
    group: "Keys",
    clef: "grand",
    gain: 0.3,
    attack: 0.004,
    decay: 0.55,
    sustain: 0.05,
    release: 0.35,
    filter: 2800,
    filterQ: 0.5,
    filterEnv: 2000,
    vibrato: 0,
    partials: [
      { type: "sine", ratio: 1, gain: 1 },
      { type: "sine", ratio: 2, gain: 0.22 },
      { type: "triangle", ratio: 3, gain: 0.08 },
    ],
  },
  {
    id: "accordion",
    name: "Accordion",
    group: "Keys",
    clef: "grand",
    gain: 0.16,
    attack: 0.08,
    decay: 0.1,
    sustain: 0.85,
    release: 0.14,
    filter: 1800,
    filterQ: 1.2,
    filterEnv: 400,
    vibrato: 0.006,
    partials: [
      { type: "square", ratio: 1, gain: 0.35 },
      { type: "sawtooth", ratio: 1, gain: 0.2, detune: 6 },
      { type: "square", ratio: 2, gain: 0.12 },
    ],
  },
  {
    id: "guitar",
    name: "Guitar",
    group: "Strings",
    clef: "treble",
    gain: 0.32,
    attack: 0.004,
    decay: 0.28,
    sustain: 0.08,
    release: 0.18,
    filter: 1600,
    filterQ: 0.8,
    filterEnv: 2200,
    vibrato: 0,
    partials: [
      { type: "triangle", ratio: 1, gain: 0.85 },
      { type: "sawtooth", ratio: 1, gain: 0.18 },
      { type: "sine", ratio: 2, gain: 0.12 },
    ],
  },
  {
    id: "strings",
    name: "Strings",
    group: "Strings",
    clef: "treble",
    gain: 0.16,
    attack: 0.22,
    decay: 0.2,
    sustain: 0.8,
    release: 0.4,
    filter: 1400,
    filterQ: 0.6,
    filterEnv: 600,
    vibrato: 0.008,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.45, detune: -7 },
      { type: "sawtooth", ratio: 1, gain: 0.45, detune: 7 },
      { type: "triangle", ratio: 1, gain: 0.25 },
    ],
  },
  {
    id: "violin",
    name: "Violin",
    group: "Strings",
    clef: "treble",
    gain: 0.2,
    attack: 0.12,
    decay: 0.15,
    sustain: 0.75,
    release: 0.25,
    filter: 2200,
    filterQ: 0.9,
    filterEnv: 900,
    vibrato: 0.012,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.55 },
      { type: "triangle", ratio: 2, gain: 0.15 },
    ],
  },
  {
    id: "cello",
    name: "Cello",
    group: "Strings",
    clef: "bass",
    gain: 0.22,
    attack: 0.14,
    decay: 0.18,
    sustain: 0.78,
    release: 0.32,
    filter: 900,
    filterQ: 0.7,
    filterEnv: 500,
    vibrato: 0.01,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.5 },
      { type: "triangle", ratio: 1, gain: 0.35 },
    ],
  },
  {
    id: "bass",
    name: "Bass",
    group: "Strings",
    clef: "bass",
    gain: 0.4,
    attack: 0.008,
    decay: 0.18,
    sustain: 0.35,
    release: 0.14,
    filter: 420,
    filterQ: 0.8,
    filterEnv: 500,
    vibrato: 0,
    partials: [
      { type: "sine", ratio: 1, gain: 0.9 },
      { type: "triangle", ratio: 1, gain: 0.35 },
      { type: "sawtooth", ratio: 1, gain: 0.12 },
    ],
  },
  {
    id: "flute",
    name: "Flute",
    group: "Winds",
    clef: "treble",
    gain: 0.28,
    attack: 0.08,
    decay: 0.1,
    sustain: 0.72,
    release: 0.16,
    filter: 2800,
    filterQ: 0.5,
    filterEnv: 400,
    vibrato: 0.007,
    partials: [
      { type: "sine", ratio: 1, gain: 0.9 },
      { type: "triangle", ratio: 2, gain: 0.08 },
    ],
  },
  {
    id: "clarinet",
    name: "Clarinet",
    group: "Winds",
    clef: "treble",
    gain: 0.2,
    attack: 0.06,
    decay: 0.1,
    sustain: 0.7,
    release: 0.14,
    filter: 1600,
    filterQ: 0.9,
    filterEnv: 500,
    vibrato: 0.004,
    partials: [
      { type: "square", ratio: 1, gain: 0.55 },
      { type: "sine", ratio: 1, gain: 0.25 },
    ],
  },
  {
    id: "sax",
    name: "Sax",
    group: "Winds",
    clef: "treble",
    gain: 0.2,
    attack: 0.07,
    decay: 0.12,
    sustain: 0.7,
    release: 0.16,
    filter: 1500,
    filterQ: 1.1,
    filterEnv: 900,
    vibrato: 0.009,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.4 },
      { type: "triangle", ratio: 1, gain: 0.35 },
    ],
  },
  {
    id: "trumpet",
    name: "Trumpet",
    group: "Brass",
    clef: "treble",
    gain: 0.22,
    attack: 0.06,
    decay: 0.12,
    sustain: 0.7,
    release: 0.14,
    filter: 1800,
    filterQ: 0.8,
    filterEnv: 1400,
    vibrato: 0.006,
    partials: [{ type: "sawtooth", ratio: 1, gain: 0.25 }],
    fm: { ratio: 1, index: 1.8, decay: 0.25 },
  },
  {
    id: "horn",
    name: "French horn",
    group: "Brass",
    clef: "treble",
    gain: 0.22,
    attack: 0.14,
    decay: 0.16,
    sustain: 0.75,
    release: 0.22,
    filter: 1100,
    filterQ: 0.7,
    filterEnv: 700,
    vibrato: 0.005,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.4 },
      { type: "sine", ratio: 1, gain: 0.4 },
    ],
  },
  {
    id: "lead",
    name: "Synth lead",
    group: "Synth",
    clef: "treble",
    gain: 0.18,
    attack: 0.02,
    decay: 0.12,
    sustain: 0.65,
    release: 0.12,
    filter: 2400,
    filterQ: 1,
    filterEnv: 1600,
    vibrato: 0.008,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.5, detune: -4 },
      { type: "square", ratio: 1, gain: 0.28, detune: 4 },
    ],
  },
  {
    id: "pad",
    name: "Warm pad",
    group: "Synth",
    clef: "treble",
    gain: 0.12,
    attack: 0.45,
    decay: 0.3,
    sustain: 0.85,
    release: 0.7,
    filter: 900,
    filterQ: 0.4,
    filterEnv: 400,
    vibrato: 0.004,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.35, detune: -8 },
      { type: "sawtooth", ratio: 1, gain: 0.35, detune: 8 },
      { type: "triangle", ratio: 1, gain: 0.25 },
    ],
  },
  {
    id: "bell",
    name: "Bell",
    group: "Mallets",
    clef: "treble",
    gain: 0.26,
    attack: 0.002,
    decay: 0.9,
    sustain: 0,
    release: 0.4,
    filter: 4200,
    filterQ: 0.3,
    filterEnv: 1000,
    vibrato: 0,
    partials: [],
    fm: { ratio: 3.5, index: 3.2, decay: 0.6 },
  },
  {
    id: "marimba",
    name: "Marimba",
    group: "Mallets",
    clef: "treble",
    gain: 0.3,
    attack: 0.003,
    decay: 0.22,
    sustain: 0,
    release: 0.12,
    filter: 2600,
    filterQ: 0.5,
    filterEnv: 800,
    vibrato: 0,
    partials: [],
    fm: { ratio: 4, index: 2.4, decay: 0.16 },
  },
  {
    id: "choir",
    name: "Choir",
    group: "Synth",
    clef: "treble",
    gain: 0.14,
    attack: 0.28,
    decay: 0.2,
    sustain: 0.8,
    release: 0.45,
    filter: 1100,
    filterQ: 0.6,
    filterEnv: 300,
    vibrato: 0.007,
    partials: [
      { type: "sawtooth", ratio: 1, gain: 0.22, detune: -6 },
      { type: "sine", ratio: 1, gain: 0.55 },
      { type: "triangle", ratio: 2, gain: 0.08 },
    ],
  },
];

const byId = new Map(PRESETS.map((p) => [p.id, p]));

export function presetById(id: string): Preset {
  return byId.get(id) ?? PRESETS[0];
}

export const PRESET_GROUPS = [...new Set(PRESETS.map((p) => p.group))];
